# Generated by Django 5.2.12 on 2026-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('source_format', models.CharField(choices=[('mp3', 'MP3'), ('ogg', 'OGG')], max_length=10, verbose_name='Исходный формат')),
                ('target_format', models.CharField(choices=[('mp3', 'MP3'), ('ogg', 'OGG')], max_length=10, verbose_name='Целевой формат')),
                ('bitrate', models.PositiveIntegerField(verbose_name='Битрейт (kbps)')),
                ('channels', models.PositiveIntegerField(verbose_name='Число каналов')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
